// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQrndWObZl5nnW4EIbHpUQXUDAofi_05I',
    appId: '1:199102790189:ios:50cc162f88083e3ab096a4',
    messagingSenderId: '199102790189',
    projectId: 'sihstudentatendacne',
    storageBucket: 'sihstudentatendacne.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkdCcZqo_apMJHfSmVMfRbouaVhG3I1X8',
    appId: '1:199102790189:web:0283ea7953dd41f9b096a4',
    messagingSenderId: '199102790189',
    projectId: 'sihstudentatendacne',
    authDomain: 'sihstudentatendacne.firebaseapp.com',
    storageBucket: 'sihstudentatendacne.firebasestorage.app',
    measurementId: 'G-C5VD1G2Q8D',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkdCcZqo_apMJHfSmVMfRbouaVhG3I1X8',
    appId: '1:199102790189:web:0283ea7953dd41f9b096a4',
    messagingSenderId: '199102790189',
    projectId: 'sihstudentatendacne',
    authDomain: 'sihstudentatendacne.firebaseapp.com',
    storageBucket: 'sihstudentatendacne.firebasestorage.app',
    measurementId: 'G-C5VD1G2Q8D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQrndWObZl5nnW4EIbHpUQXUDAofi_05I',
    appId: '1:199102790189:ios:50cc162f88083e3ab096a4',
    messagingSenderId: '199102790189',
    projectId: 'sihstudentatendacne',
    storageBucket: 'sihstudentatendacne.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANS1EmVzDCVA2XL4nOvl5kTKsnMrttIqE',
    appId: '1:199102790189:android:26fba352447fa43db096a4',
    messagingSenderId: '199102790189',
    projectId: 'sihstudentatendacne',
    storageBucket: 'sihstudentatendacne.firebasestorage.app',
  );

}